In [2]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.1.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from python-docx) (5.3.1)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.11/dist-packages (from python-docx) (4.13.0)
Downloading python_docx-1.1.2-py3-none-any.whl (244 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 kB 3.9 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.1.2

In [2]:
from docx import Document
import pandas as pd

In [ ]:
# Function to extract and preprocess data from tables
def process_tables_to_text(doc_path):
    doc = Document(doc_path)
    texts = []

    # Extract paragraphs
    for paragraph in doc.paragraphs:
        if paragraph.text.strip():
            texts.append(paragraph.text.strip())

    # Extract data from tables and convert to text
    for table in doc.tables:
        for row in table.rows:
            row_text = " | ".join([cell.text.strip() for cell in row.cells if cell.text.strip()])
            if row_text:
                texts.append(f"Table: {row_text}")  # Add prefix to identify table data

    return texts

# File path
doc_path = "Data/00002469135802469136ctcp-bcg-land03022025-000000bo-co-ti-chnh-qu-4-2024-ca-cng-ty-m.docx"

# Extract and convert data
processed_texts = process_tables_to_text(doc_path)

In [ ]:
# 2. Preprocess data
def preprocess_data(df):
    # Remove empty rows/columns
    df.dropna(how='all', inplace=True)
    df.dropna(axis=1, how='all', inplace=True)

    # Normalize text
    for col in df.columns:
        if df[col].dtype == 'object':  # Check the data type of each column
            df[col] = df[col].str.lower()  # Convert to lowercase
            df[col] = df[col].str.replace(r'[^\w\s]', '', regex=True)  # Remove special characters
            df[col] = df[col].str.strip()  # Remove extra spaces

    return df

In [4]:
# 1. Extract all tables from a Word file
def extract_tables_from_doc(doc_path):
    doc = Document(doc_path)
    tables = doc.tables
    dataframes = []

    if tables:
        print(f"Total number of extracted tables: {len(tables)}")

        for i, table in enumerate(tables, start=1):
            # print(f"\nConverting Table {i} to DataFrame...")

            table_data = []
            for row in table.rows:
                row_data = [cell.text.strip() for cell in row.cells]
                table_data.append(row_data)

            df = pd.DataFrame(table_data[1:], columns=table_data[0])
            dataframes.append(df)

            # print(f"DataFrame of Table {i}:")
            # print(df)
    else:
        print("No tables found in the file.")

    return dataframes

In [5]:
# 4. File path for the Word document
doc_path = "/content/00002469135802469136ctcp-bcg-land03022025-000000bo-co-ti-chnh-qu-4-2024-ca-cng-ty-m.docx"

# Extract and convert tables to DataFrames
dataframes = extract_tables_from_doc(doc_path)

Total number of extracted tables: 39

In [6]:
dataframes[5]

,Items,Code,Note,Quarter IV 2024,Quarter IV 2023,Accumulated to the end of Quarter IV.2024,Accumulated to the end of Quarter IV.2023
0,1. Revenues from sales and services rendered,01,V1.01,"8,706,481,481","8,475,000,000","34,131,481,481","33,900,000,000"
1,2. Revenue deductions,02,,-,-,-,-
2,3. Net revenues from sales and services rendered,10,,"8,706,481,481","8,475,000,000","34,131,481,481","33,900,000,000"
3,4. Costs of goods sold,11,V1.02,"5,282,860,829","5,060,198,642","19,3 54,540,087","21,403,991,212"
4,5. Gross revenues from sales and services rend...,20,,"3,423,620,652","3,414,801,358","14,776,941,394","12,496,008,788"
5,6. Financial income,21,V1.03,"168,839,636,375","160,132,029,657","582,397,303,126","539,786,865,921"
6,7. Financial expenses,22,VI.04,"(3 5,462,743,426)","102,535,983,039","232,263,390,733","425,789,232,726"
7,+ In which: Interest expenses,23,,"69,817,049,993","74,008,514,914","285,553,122,895","311,196,207,462"
8,8. Selling expenses,25,,-,-,-,-
9,9. General and administration expenses,26,VI.05,"16,062,706,980","28,274,085,931","46,368,335,390","62,515,699,294"
10,10. Net profits from operating activities,30,,"191,663,293,473","32,736,762,045","318,542,518,397","63,977,942,689"
11,11. Other income,31,,-,-,"31,923,549,345",-
12,12. Other expenses,32,VI.06,"771,423,796","1,559,930,810","6,318,767,984","6,443,116,666"
13,13. Other profits,40,,"(771,423,796)","(1,559,930,810)","25,604,781,361","(6,443,116,666)"
14,14. Total accounting profit before tax,50,,"190,891,869,677","31,176,831,235","344,147,299,758","57,534,826,023"
15,15. Current corporate income tax expenses,51,VI.08,"3 8,3 85,275,228","9,501,703,429","70,307,428,322","15,912,779,191"
16,16. Deferred corporate income tax expenses,52,,-,"(2,159,025,753)",-,"(2,159,025,753)"
17,17. Profits after corporate income tax,60,,"152,506,594,449","23,834,153,559","273,839,871,436","43,781,072,585"

In [7]:
dataframes=[(dataframes[2], "Balance Sheet"), (dataframes[4],"Balance Sheet"), (dataframes[5], "Income Statement"),
            (dataframes[6],"Cash Flow Statement"), (dataframes[7],"Cash Flow Statement")]

In [ ]:
import transformers
print(transformers.__version__)

4.51.0

In [ ]:
import torch
print(torch.__version__)

2.5.1

In [6]:
# pip uninstall transformers torch
!pip install transformers==4.36.2 torch==2.1.0

Collecting transformers==4.36.2
  Downloading transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.8/126.8 kB 3.0 MB/s eta 0:00:00
Collecting torch==2.1.0
  Downloading torch-2.1.0-cp311-cp311-manylinux1_x86_64.whl.metadata (25 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (0.30.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (2.32.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.36.2)
  Downloading tokenizers-0.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.36.2) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from torch==2.1.0) (4.13.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from torch==2.1.0) (1.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.1.0) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.1.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch==2.1.0) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.1.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.1.0)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.1.0)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.1.0)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.1.0)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.1.0)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.1.0)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.1.0)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.1.0)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.18.1 (from torch==2.1.0)
  Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.1.0)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.1.0 (from torch==2.1.0)
  Downloading triton-2.1.0-0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.1.0) (12.5.82)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.1.0) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.36.2) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.36.2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.36.2) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.36.2) (2025.1.31)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->torch==2.1.0) (1.3.0)
Downloading transformers-4.36.2-py3-none-any.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 64.4 MB/s eta 0:00:00
Downloading torch-2.1.0-cp311-cp311-manylinux1_x86_64.whl (670.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 916.6 kB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 56.9 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 48.4 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 28.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 812.5 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 11.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.3 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl (209.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 6.3 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 5.9 MB/s eta 0:00:00
Downloading triton-2.1.0-0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 8.6 MB/s eta 0:00:00
Downloading tokenizers-0.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 61.9 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, nvidia-cudnn-cu12, torch, tokenizers, transformers
  Attempting uninstall: triton
    Found existing installation: triton 3.2.0
    Uninstalling triton-3.2.0:
      Successfully uninstalled triton-3.2.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.4.127
    Uninstalling nvidia-nvtx-cu12-12.4.127:
      Successfully uninstalled nvidia-nvtx-cu12-12.4.127
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.21.5
    Uninstalling nvidia-nccl-cu12-2.21.5:
      Successfully uninstalled nvidia-nccl-cu12-2.21.5
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: torch
    Found existing installation: torch 2.6.0+cu124
    Uninstalling torch-2.6.0+cu124:
      Successfully uninstalled torch-2.6.0+cu124
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.1
    Uninstalling tokenizers-0.21.1:
      Successfully uninstalled tokenizers-0.21.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.50.3
    Uninstalling transformers-4.50.3:
      Successfully uninstalled transformers-4.50.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.6.0+cu124 requires torch==2.6.0, but you have torch 2.1.0 which is incompatible.
sentence-transformers 3.4.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.36.2 which is incompatible.
torchvision 0.21.0+cu124 requires torch==2.6.0, but you have torch 2.1.0 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.18.1 nvidia-nvtx-cu12-12.1.105 tokenizers-0.15.2 torch-2.1.0 transformers-4.36.2 triton-2.1.0

In [1]:
import pandas as pd
from transformers import BertTokenizer, BertForSequenceClassification
import torch

# Tải FinBERT mà không dùng context đặc biệt
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')
model = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone')
model.eval()  # Đặt mô hình ở chế độ đánh giá

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-0addb8f6ecda>", line 2, in <cell line: 0>
    from transformers import BertTokenizer, BertForSequenceClassification
  File "/usr/local/lib/python3.11/dist-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.11/dist-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/usr/local/lib/python3.11/dist-packages/transformers/utils/__init__.py", line 31, in <module>
    from .generic import (
  File "/usr/local/lib/python3.11/dist-packages/transformers/utils/generic.py", line 432, in <module>
    import torch.utils._pytree as _torch_pytree
  File "/usr/local/lib/python3.11/dist-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/usr/local/lib/python3.11/dist-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/533 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30873, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [12]:
from transformers import pipeline
# Tạo pipeline cho text-classification
nlp = pipeline("text-classification", model=model, tokenizer=tokenizer)

In [10]:
# Hàm chuyển DataFrame thành văn bản có ý nghĩa
def dataframe_to_text(df, statement_type):
    text = f"{statement_type} Analysis:\n"
    for index, row in df.iterrows():
        # Chuyển dòng thành câu văn
        row_text = " ".join([f"{col}: {val}" for col, val in row.items() if pd.notna(val)])
        text += f"{row_text}\n"
    return text

# Hàm phân tích cảm xúc bằng FinBERT
def analyze_sentiment(text):
    # Tokenize văn bản
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512, padding=True)

    # Dự đoán với FinBERT
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        probs = torch.softmax(logits, dim=1)
        sentiment_scores = probs[0].tolist()  # [negative, neutral, positive]

    labels = ['Negative', 'Neutral', 'Positive']
    sentiment = labels[sentiment_scores.index(max(sentiment_scores))]
    return sentiment, sentiment_scores


# Xử lý và phân tích từng bảng
for df, statement_type in dataframes:
    # Chuyển DataFrame thành văn bản
    text = dataframe_to_text(df, statement_type)
    print(f"\n{statement_type} Text:")
    print(text)

    # Phân tích cảm xúc
    sentiment, scores = analyze_sentiment(text)
    print(f"\n{statement_type} Sentiment Analysis:")
    print(f"Sentiment: {sentiment}")
    print(f"Scores: Negative: {scores[0]:.4f}, Neutral: {scores[1]:.4f}, Positive: {scores[2]:.4f}")

# Phân tích tổng quan
combined_text = "\n".join([dataframe_to_text(df, statement_type) for df, statement_type in dataframes])
overall_sentiment, overall_scores = analyze_sentiment(combined_text)
print("\nOverall Financial Statement Sentiment Analysis:")
print(f"Sentiment: {overall_sentiment}")
print(f"Scores: Negative: {overall_scores[0]:.4f}, Neutral: {overall_scores[1]:.4f}, Positive: {overall_scores[2]:.4f}")

Balance Sheet Text:
Balance Sheet Analysis:
Items: A. SHORT-TERM ASSETS Code: 100 Note:  Closing balance: 711,271,276,203 Opening balance: 485,932,979,327
Items: I. Cash and cash equivalents Code: 110 Note: V.01 Closing balance: 6,490,181,446 Opening balance: 14,178,909,455
Items: 1. Cash Code: 111 Note:  Closing balance: 6,490,181,446 Opening balance: 14,178,909,455
Items: II. Short-term investments Code: 120 Note: V.04 Closing balance: 4,104,000,000 Opening balance: 4,560,000,000
Items: I. Trading securities Code: 121 Note:  Closing balance: 4,560,000,000 Opening balance: 4,560,000,000
Items: 2. Provisions for devaluation of trading securities Code: 122 Note:  Closing balance: (456,000,000) Opening balance: -
Items: III. Short-term receivables Code: 130 Note:  Closing balance: 687,380,288,197 Opening balance: 462,524,739,791
Items: 1. Short-term trade receivables Code: 131 Note: V.02 Closing balance: 16,034,000,000 Opening balance: 4,268,000,000
Items: 2. Short-term repayments to suppliers Code: 132 Note: V.03 Closing balance: 129,902,906,000 Opening balance: 109,145,210,000
Items: 6. Other short-term receivables Code: 136 Note: V.06 Closing balance: 542,843,3 82,197 Opening balance: 350,511,529,791
Items: 7. Allowance for short-term doubtful debts Code: 137 Note:  Closing balance: (1,400,000,000) Opening balance: (1,400,000,000)
Items: IV. Inventories Code: 140 Note:  Closing balance: 6,951,728,000 Opening balance: 4,551,728,000
4,551,728,000
Items: 1. Inventories Code: 141 Note: V.07 Closing balance: 6,951,728,000 Opening balance: 4,551,728,000
4,551,728,000
Items: V. Other current assets Code: 150 Note:  Closing balance: 6,345,078,560 Opening balance: 117,602,081
117,602,081
Items: 1. Short-term prepaid expenses Code: 151 Note: V.11 Closing balance: 359,834,036 Opening balance: 117,602,081
117,602,081
Items: 2. Deductible value added tax Code: 152 Note:  Closing balance: 5,981,244,524 Opening balance: -
Items: 3. Taxes and other receivables from government budget Code: 153 Note: V.15 Closing balance: 4,000,000 Opening balance: -
Items: B. LONG-TERM ASSETS Code: 200 Note:  Closing balance: 7,007,927,213,127 Opening balance: 7,105,871,906,341
Items: I. Long-term receivables Code: 210 Note:  Closing balance: 4,299,360,000,000 Opening balance: 4,353,820,000,000
Items: 5. Receivables for long-term loans Code: 215 Note: V.05 Closing balance: - Opening balance: 105,960,000,000
Items: Other long-term receivables
Allowance for long-term doubtful debts Code: 216
219 Note: V.06 Closing balance: 4,299,360,000,000 Opening balance: 4,247,860,000,000
Items: II. Fixed assets Code: 220 Note:  Closing balance: 5,806,643,249 Opening balance: 7,758,136,948
Items: 1. Tangible fixed assets Code: 221 Note: V.09 Closing balance: 5,806,643,249 Opening balance: 7,758,136,948
Items: - Historical cost Code: 222 Note:  Closing balance: 11,993,242,183 Opening balance: 11,952,042,183
Items: - Accumulated depreciation Code: 223 Note:  Closing balance: (6,186,598,934) Opening balance: (4,193,905,235)
Items: 3. Intangible fixed assets Code: 221 Note: V.10 Closing balance: - Opening balance: -
Items: - Initial cost Code: 228 Note:  Closing balance: 1,075,201,500 Opening balance: 1,075,201,500
Items: - Accumulated depreciation Code: 229 Note:  Closing balance: (1,075,201,500) Opening balance: (1,075,201,500)
Items: IV. Long-term assets in progress Code: 240 Note:  Closing balance: 4,255,577,593 Opening balance: 4,255,577,593
Items: 2. Construction-in-progress Code: 242 Note: V.08 Closing balance: 4,255,577,593 Opening balance: 4,255,577,593
Items: V. Long-term investments Code: 250 Note: V.04 Closing balance: 2,695,774,048,963 Opening balance: 2,737,063,362,466
Items: 1. Investments in subsidiaries Code: 251 Note:  Closing balance: 1,805,543,478,124 Opening balance: 1,805,543,478,124
Items: 2. Investments in joint ventures and associates Code: 252 Note:  Closing balance: 1,022,863,263,769 Opening balance: 1,017,663,263,769
Items: 3. Investments in other entities Code: 253 Note:  Closing balance: - Opening balance: 128,250,000,000
Items: 4. Provisions for devaluation of long-term financial investments Code: 254 Note:  Closing balance: (132,632,692,930) Opening balance: (224,893,379,427)
Items: 5. Held-to-maturity investments Code: 255 Note:  Closing balance: - Opening balance: 10,500,000,000
Items: VI. Other long-term assets Code: 260 Note:  Closing balance: 2,730,943,322 Opening balance: 2,974,829,334
Items: 1. Long-term prepaid expenses Code: 261 Note: V.ll Closing balance: 571,917,569 Opening balance: 815,803,581
Items: 2. Deferred income tax assets Code: 262 Note:  Closing balance: 2,159,025,753 Opening balance: 2,159,025,753
Items: TOTAL ASSETS Code: 270 Note:  Closing balance: 7,719,198,489,330 Opening balance: 7,591,804,885,668


Balance Sheet Sentiment Analysis:
Sentiment: Negative
Scores: Negative: 1.0000, Neutral: 0.0000, Positive: 0.0000

Balance Sheet Text:
Balance Sheet Analysis:
C. LIABILITIES: I. Short-term liabilities 300: 310 2,652,593,500,604: 146,433,500,604 2,799,039,768,378: 120,979,768,378
C. LIABILITIES: 1. Short-term trade payables 300: 311	V.13 2,652,593,500,604: 28,930,590,227 2,799,039,768,378: 16,097,291,417
C. LIABILITIES: 2. Short-term prepayments from customers 300: 312	V.14 2,652,593,500,604: 28,000,000,000 2,799,039,768,378: 28,000,000,000
C. LIABILITIES: 3. Taxes and other payables to government budget 300: 313	V.15 2,652,593,500,604: 70,512,797,404 2,799,039,768,378: 13,498,095,5 86
C. LIABILITIES: 4. Payables to employees 300: 314 2,652,593,500,604: 2,272,301,315 2,799,039,768,378: 2,052,323,786
C. LIABILITIES: 5. Short-term accrued expenses 300: 315	V.16 2,652,593,500,604: 10,868,669,884 2,799,039,768,378: 22,925,580,822
C. LIABILITIES: 8. Short-term unearned revenues 300: 318 2,652,593,500,604: -. 2,799,039,768,378:
C. LIABILITIES: 9. Other short-term payments 300: 319	V.17 2,652,593,500,604: 4,649,141,774 2,799,039,768,378: 37,623,143,43
C. LIABILITIES: 10. Short-term borrowings and finance lease liabilities 300: 320	V.12 2,652,593,500,604: 1,200,000,000 2,799,039,768,378: 783,333,336
C. LIABILITIES: II. Long-term liabilities 300: 330 2,652,593,500,604: 2,506,160,000,000 2,799,039,768,378: 2,678,060,000,000
C. LIABILITIES: 7. Other long-term payables 300: 337	V.17 2,652,593,500,604: - 2,799,039,768,378: 10,000,000,000
C. LIABILITIES: 8. Long-term borrowings and finance lease liabilities 300: 338	V.12 2,652,593,500,604: 2,506,160,000,000 2,799,039,768,378: 2,668,060,000,000
C. LIABILITIES: D. EQUITY 300: 400 2,652,593,500,604: 5,066,604,988,726 2,799,039,768,378: 4,792,765,117,290
C. LIABILITIES: I. Owner’s equity 300: 410	V.18 2,652,593,500,604: 5,066,604,988,726 2,799,039,768,378: 4,792,765,117,290
C. LIABILITIES: 1. Contributed capital 300: 411 2,652,593,500,604: 4,737,999,130,000 2,799,039,768,378: 4,600,000,000,00
C. LIABILITIES: - Ordinary shares with voting rights 300: 411a 2,652,593,500,604: 4,73 7,999,130,000 2,799,039,768,378: 4,600.000,000,000
C. LIABILITIES: - Preference shares 300: 411b 2,652,593,500,604: - 2,799,039,768,378: -
C. LIABILITIES: 2. Share premiums 300: 412 2,652,593,500,604: - 2,799,039,768,378: -
C. LIABILITIES: 11. Undistributed profit after tax 300: 421 2,652,593,500,604: 328,605,858,726 2,799,039,768,378: 192,765,117,290
C. LIABILITIES: - Undistributed profit after tax brought fonvard 300: 421a 2,652,593,500,604: 54,765,987,290 2,799,039,768,378: 148,984,044,705
C. LIABILITIES: - Undistributed profit after tax for the current period 300: 421b 2,652,593,500,604: 2 73,839,871,436 2,799,039,768,378: 43,781,072,585
C. LIABILITIES: II. Funding sources and other funds 300: 430 2,652,593,500,604: - 2,799,039,768,378: -
C. LIABILITIES: TOTAL RESOURCES 300: 440 2,652,593,500,604: 7,719,198,489,330 2,799,039,768,378: 7,591,804,885,668


Balance Sheet Sentiment Analysis:
Sentiment: Negative
Scores: Negative: 1.0000, Neutral: 0.0000, Positive: 0.0000

Income Statement Text:
Income Statement Analysis:
Items: 1. Revenues from sales and services rendered Code: 01 Note: V1.01 Quarter IV 2024: 8,706,481,481 Quarter IV 2023: 8,475,000,000 Accumulated to the end of Quarter IV.2024: 34,131,481,481 Accumulated to the end of Quarter IV.2023: 33,900,000,000
Items: 2. Revenue deductions Code: 02 Note:  Quarter IV 2024: - Quarter IV 2023: - Accumulated to the end of Quarter IV.2024: - Accumulated to the end of Quarter IV.2023: -
Items: 3. Net revenues from sales and services rendered Code: 10 Note:  Quarter IV 2024: 8,706,481,481 Quarter IV 2023: 8,475,000,000 Accumulated to the end of Quarter IV.2024: 34,131,481,481 Accumulated to the end of Quarter IV.2023: 33,900,000,000
Items: 4. Costs of goods sold Code: 11 Note: V1.02 Quarter IV 2024: 5,282,860,829 Quarter IV 2023: 5,060,198,642 Accumulated to the end of Quarter IV.2024: 19,3 54,540,087 Accumulated to the end of Quarter IV.2023: 21,403,991,212
Items: 5. Gross revenues from sales and services rendered Code: 20 Note:  Quarter IV 2024: 3,423,620,652 Quarter IV 2023: 3,414,801,358 Accumulated to the end of Quarter IV.2024: 14,776,941,394 Accumulated to the end of Quarter IV.2023: 12,496,008,788
Items: 6. Financial income Code: 21 Note: V1.03 Quarter IV 2024: 168,839,636,375 Quarter IV 2023: 160,132,029,657 Accumulated to the end of Quarter IV.2024: 582,397,303,126 Accumulated to the end of Quarter IV.2023: 539,786,865,921
Items: 7. Financial expenses Code: 22 Note: VI.04 Quarter IV 2024: (3 5,462,743,426) Quarter IV 2023: 102,535,983,039 Accumulated to the end of Quarter IV.2024: 232,263,390,733 Accumulated to the end of Quarter IV.2023: 425,789,232,726
Items: + In which: Interest expenses Code: 23 Note:  Quarter IV 2024: 69,817,049,993 Quarter IV 2023: 74,008,514,914 Accumulated to the end of Quarter IV.2024: 285,553,122,895 Accumulated to the end of Quarter IV.2023: 311,196,207,462
Items: 8. Selling expenses Code: 25 Note:  Quarter IV 2024: - Quarter IV 2023: - Accumulated to the end of Quarter IV.2024: - Accumulated to the end of Quarter IV.2023: -
Items: 9. General and administration expenses Code: 26 Note: VI.05 Quarter IV 2024: 16,062,706,980 Quarter IV 2023: 28,274,085,931 Accumulated to the end of Quarter IV.2024: 46,368,335,390 Accumulated to the end of Quarter IV.2023: 62,515,699,294
Items: 10. Net profits from operating activities Code: 30 Note:  Quarter IV 2024: 191,663,293,473 Quarter IV 2023: 32,736,762,045 Accumulated to the end of Quarter IV.2024: 318,542,518,397 Accumulated to the end of Quarter IV.2023: 63,977,942,689
Items: 11. Other income Code: 31 Note:  Quarter IV 2024: - Quarter IV 2023: - Accumulated to the end of Quarter IV.2024: 31,923,549,345 Accumulated to the end of Quarter IV.2023: -
Items: 12. Other expenses Code: 32 Note: VI.06 Quarter IV 2024: 771,423,796 Quarter IV 2023: 1,559,930,810 Accumulated to the end of Quarter IV.2024: 6,318,767,984 Accumulated to the end of Quarter IV.2023: 6,443,116,666
Items: 13. Other profits Code: 40 Note:  Quarter IV 2024: (771,423,796) Quarter IV 2023: (1,559,930,810) Accumulated to the end of Quarter IV.2024: 25,604,781,361 Accumulated to the end of Quarter IV.2023: (6,443,116,666)
Items: 14. Total accounting profit before tax Code: 50 Note:  Quarter IV 2024: 190,891,869,677 Quarter IV 2023: 31,176,831,235 Accumulated to the end of Quarter IV.2024: 344,147,299,758 Accumulated to the end of Quarter IV.2023: 57,534,826,023
Items: 15. Current corporate income tax expenses Code: 51 Note: VI.08 Quarter IV 2024: 3 8,3 85,275,228 Quarter IV 2023: 9,501,703,429 Accumulated to the end of Quarter IV.2024: 70,307,428,322 Accumulated to the end of Quarter IV.2023: 15,912,779,191
Items: 16. Deferred corporate income tax expenses Code: 52 Note:  Quarter IV 2024: - Quarter IV 2023: (2,159,025,753) Accumulated to the end of Quarter IV.2024: - Accumulated to the end of Quarter IV.2023: (2,159,025,753)
Items: 17. Profits after corporate income tax Code: 60 Note:  Quarter IV 2024: 152,506,594,449 Quarter IV 2023: 23,834,153,559 Accumulated to the end of Quarter IV.2024: 273,839,871,436 Accumulated to the end of Quarter IV.2023: 43,781,072,585


Income Statement Sentiment Analysis:
Sentiment: Negative
Scores: Negative: 1.0000, Neutral: 0.0000, Positive: 0.0000

Cash Flow Statement Text:
Cash Flow Statement Analysis:
(Indirect method) Quarter IV 2024: Items	Code Note	Current year Currency: VND: Previous year
(Indirect method) Quarter IV 2024: Cash flows from operating activities
Profit before tax	01	344,147,299,758
Adjustments for
Depreciation of fixed assets and investment properties	02	1,992,693,699
Allowances and provisions	03	(91,804,686,497)
(Gains)/ losses on investing activities	05	(6,623,622,107)
Interest expenses	06	285,969,789,559
Operating profit before changes in working	capital	08	533,681,474,412
(Increase)/ decrease in receivables	09	(252,340,792,930)
(Increase)/ decrease in inventories	10	(2,400,000,000)
Increase/ (decrease) in payables (exclusive of interest	11	(20,473,284 774)
payables, corporate income tax payables)
(Increase)/ decrease in prepaid expenses	12	1,654,057
(Increase)/ decrease in trading securities	13
Interest paid	14	(307,33 8,361,251)
Corporate income tax paid	15	(13,011,839,630)
Net cash flows from operating activities	20	(61,881,150,116) Currency: VND: 57,534,826,023
2,102,649,413
(38,279,353,734)
(29,118,645,241)
312,862,874,13 0
305,102,350,591
403,243,3 80,326
18,451,931,159
(8,553,066,257)
24,754,226,079
(361,741,317,049)
(3 8,644,23 5,491)
342,613,269,358
(Indirect method) Quarter IV 2024: II. Cash flows from investing activities
1. Purchase or construction of fixed assets and other long-	21
term assets Currency: VND: (4,255,577,593)
(Indirect method) Quarter IV 2024: 3. Loans and purchase of debt instruments from other entities 23	(6,100,000,000) Currency: VND: (119,110,000,000)
(Indirect method) Quarter IV 2024: Collection of loans and repurchase of debt instruments of	24	122,560,000 000
other entities
Equity investments in other entities	25	(35,200,000,000)
Proceeds from equity investment in other entities	26	128,250,000,000
Interest and dividend received	27	6,623,622,107
Net cash flows from investing activities	30	216,092,422,107 Currency: VND: 13,150,000,000
(511,250,000,000) 315,000,000,000 881,816,748
(305,583,760,845)


Cash Flow Statement Sentiment Analysis:
Sentiment: Negative
Scores: Negative: 1.0000, Neutral: 0.0000, Positive: 0.0000

Cash Flow Statement Text:
Cash Flow Statement Analysis:
III. Cash flows from financial activities: 1. Proceeds from issuance of shares and receipt of contributed capital III. Cash flows from financial activities: 31 III. Cash flows from financial activities: - III. Cash flows from financial activities: -
III. Cash flows from financial activities: 3. Proceeds from borrowings III. Cash flows from financial activities: 33 III. Cash flows from financial activities: 181,250,000,000 III. Cash flows from financial activities: -
III. Cash flows from financial activities: 4. Payments to settle loan principals III. Cash flows from financial activities: 34 III. Cash flows from financial activities: (343,150,000,000) III. Cash flows from financial activities: (26,200,000,000)
III. Cash flows from financial activities: 5. Payments for financial leased assets III. Cash flows from financial activities: 35 III. Cash flows from financial activities: - III. Cash flows from financial activities: -
III. Cash flows from financial activities: 6. Payments of dividends III. Cash flows from financial activities: 36 III. Cash flows from financial activities: - III. Cash flows from financial activities: -
III. Cash flows from financial activities: Net cash flows from financial activities III. Cash flows from financial activities: 40 III. Cash flows from financial activities: (161,900,000,000) III. Cash flows from financial activities: (26,200,000,000)
III. Cash flows from financial activities: Net cash flows during the year III. Cash flows from financial activities: 50 III. Cash flows from financial activities: (7,688,728,009) III. Cash flows from financial activities: 10,829,508,513
III. Cash flows from financial activities: Cash and cash equivalents at the beginning of the year III. Cash flows from financial activities: 60 III. Cash flows from financial activities: 14,178,909,455 III. Cash flows from financial activities: 3,349,400,942
III. Cash flows from financial activities: Effect of exchange rate fluctuations III. Cash flows from financial activities: 61 III. Cash flows from financial activities: - III. Cash flows from financial activities: -


Cash Flow Statement Sentiment Analysis:
Sentiment: Negative
Scores: Negative: 1.0000, Neutral: 0.0000, Positive: 0.0000

Overall Financial Statement Sentiment Analysis:
Sentiment: Negative
Scores: Negative: 1.0000, Neutral: 0.0000, Positive: 0.0000

In [15]:
# 4. File path for the Word document
doc_path = "/content/000000014633600_VI_BaoCaoTaiChinh_KiemToan_2024_19032025143809.docx"

# Extract and convert tables to DataFrames
dataframes1 = extract_tables_from_doc(doc_path)

Total number of extracted tables: 47

In [25]:
dataframes1[6]

  Thuyết                    Năm 2024                   Nám 2023
0   minh                         VND                        VND
1                     66.301.708.366             10.230.715.312
2         110.240.961.933\n1.827.121  100.010.320.043\n(73.422)

In [26]:
dataframes1=[(dataframes1[2], "Bảng cân đối kế toán"), (dataframes1[3], "BBảng cân đối kế toán"), (dataframes1[4],"Báo cáo kết quả hoạt động kinh doanh"),
 (dataframes1[5], "Báo cáo lưu chuyển tiền tệ"), (dataframes1[6],"Báo cáo lưu chuyển tiền tệ")]

In [37]:
from transformers import AutoTokenizer, AutoModel
model_name = "vinai/phobert-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

config.json:   0%|          | 0.00/558 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.13M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.48G [00:00<?, ?B/s]

In [43]:
# Hàm chuyển DataFrame thành văn bản có ý nghĩa
def dataframe_to_text_v2(df, statement_type):
    text = f"{statement_type} Analysis:\n"
    for index, row in df.iterrows():
        values = {}
        for col, val in row.items():
            if pd.notna(val) and not isinstance(val, str) and col not in ['Mã số', 'TÀI SẢN', 'Thuyết _ minh']:
                try:
                    float(val)  # Kiểm tra xem có phải là số không
                    values[col] = val
                except ValueError:
                    pass  # Bỏ qua nếu không phải là số

        if values:
            value_pairs = [f"{col}: {val}" for col, val in values.items()]
            text += f"Tại dòng {index}, các giá trị đáng chú ý là: {', '.join(value_pairs)}.\n"
    return text

# Chuyển toàn bộ list dataframes1 sang text
combined_text = ""
for df, statement_type in dataframes1:
    combined_text += dataframe_to_text(df, statement_type)
    combined_text += "\n" # Thêm một dòng trắng giữa các bảng cho dễ đọc

In [44]:
print(combined_text)

Bảng cân đối kế toán Analysis:
Mã số: Mã số TÀI SẢN: TÀI SẢN Thuyết _ minh: Thuyết _ minh 31/12/2024 _
VND: 31/12/2024 _
VND 01/01/2024: VND
Mã số: 100 TÀI SẢN: A. TÀI SẢN NGẮN HẠN Thuyết _ minh:  31/12/2024 _
VND: 3.272.810.300.818 01/01/2024: 2.577.565.191.421
Mã số: 110 TÀI SẢN: I. Tiền và các khoản tương đương tiền Thuyết _ minh: 3 31/12/2024 _
VND: 176.544.497.420 01/01/2024: 110.240.961.933
Mã số: 111 TÀI SẢN: 1. Tiền Thuyết _ minh:  31/12/2024 _
VND: 176.544.497.420 01/01/2024: 110.240.961.933
Mã số: 120 TÀI SẢN: II. Đầu tư tài chính ngắn hạn Thuyết _ minh: 4 31/12/2024 _
VND: 8.627.790.000 01/01/2024: -
Mã số: 123 TÀI SẢN: 1. Đầu tư nắm giữ đến ngày đáo hạn Thuyết _ minh:  31/12/2024 _
VND: 8^627.790.000 01/01/2024: -
Mã số: 130 TÀI SẢN: III. Các khoản phải thu ngắn hạn Thuyết _ minh:  31/12/2024 _
VND: 1.246.054.852.986 01/01/2024: 1.085.169.791.611
Mã số: 131 TÀI SẢN: 1. Phải thu ngắn hạn của khách hàng Thuyết _ minh: 5 31/12/2024 _
VND: 1.496.078.318.628 01/01/2024: 1.341.989.085.897
Mã số: 132 TÀI SẢN: 2. Trả trước cho người bán ngắn hạn Thuyết _ minh: 6 31/12/2024 _
VND: 3.740.068.728 01/01/2024: 962.801.512
Mã số: 136 TÀI SẢN: 3. Phải thu ngắn hạn khác Thuyết _ minh: 7 31/12/2024 _
VND: 96.626.604.721 01/01/2024: 90.048.053.481
Mã số: 137 TÀI SẢN: 4. Dự phòng phải thu ngắn hạn khó đòi Thuyết _ minh:  31/12/2024 _
VND: (350.579.870.182) 01/01/2024: (347.943.144.304)
Mã số: 139 TÀI SẢN: 5. Tài sản thiếu chờ xử lỹ Thuyết _ minh:  31/12/2024 _
VND: 189.731.091 01/01/2024: 112.995.025
Mã số: 140 TÀI SẢN: IV. Hàng tồn kho Thuyết _ minh: 9 31/12/2024 _
VND: 1.772.911.576.404 01/01/2024: 1.331.291.821.926
Mã số: 141 TÀI SẢN: 1. Hàng tồn kho Thuyết _ minh:  31/12/2024 _
VND: 1.776.590.518.449 01/01/2024: 1.335.932.721.544
Mã số: 149 TÀI SẢN: 2. Dự phòng giảm giá hàng tồn kho Thuyết _ minh:  31/12/2024 _
VND: (3.678.942.045) 01/01/2024: (4.640.899.618)
Mã số: 150 TÀI SẢN: V. Tài sản ngắn hạn khác Thuyết _ minh:  31/12/2024 _
VND: 68.671.584.008 01/01/2024: 50.862.615.951
Mã số: 151 TÀI SẢN: 1. Chỉ phí trả trước ngắn hạn Thuyết _ minh: 10 31/12/2024 _
VND: 31.743.168.442 01/01/2024: 38.223.368.616
Mã số: 152 TÀI SẢN: 2. Thuế GTGT được khấu trừ Thuyết _ minh:  31/12/2024 _
VND: 224.124.875 01/01/2024: 148.959.164
Mã số: 153 TÀI SẢN: 3. Thuế và các khoản khác phải thu Thuyết _ minh: 16 31/12/2024 _
VND: 36.704.290.691 01/01/2024: 12.490.288.171
Mã số:  TÀI SẢN: Nhà nước Thuyết _ minh:  31/12/2024 _
VND:  01/01/2024:
Mã số: 200 TÀI SẢN: B. TÀI SẢN ĐÀI HẠN Thuyết _ minh:  31/12/2024 _
VND: 7.263.117.999.036 01/01/2024: 7.563.169.600.540
Mã số: 210 TÀI SẢN: I. Các khoản phải thu dài hạn Thuyết _ minh:  31/12/2024 _
VND: 63.800.488.952 01/01/2024: 60.762.560.474
Mã số: 212 TÀI SẢN: 1. Trả trước cho người bán dài hạn Thuyết _ minh: 6 31/12/2024 _
VND: 21.046.613.341 01/01/2024: 21.046.613.341	7
Mã số: 216 TÀI SẢN: 2. Phải thu dài hạn khác Thuyết _ minh: 7 31/12/2024 _
VND: 42.753.875.611 01/01/2024: 39.715.947.133
Mã số:  TÀI SẢN:  Thuyết _ minh:  31/12/2024 _
VND:  01/01/2024:
Mã số: 220 TÀI SẢN: II. Tài sản cố đinh Thuyết _ minh:  31/12/2024 _
VND: 387.777.271.478 01/01/2024: 440.902.300.404
Mã số: 221 TÀI SẢN: 1. Tài sản cố định hữu hình Thuyết _ minh: 11 31/12/2024 _
VND: 353.034.446.237 01/01/2024: 403.290.977.517	x
Mã số: 222 TÀI SẢN: - Nguyên giá Thuyết _ minh:  31/12/2024 _
VND: 3.408.337.130.943 01/01/2024: 3.403.447.938.699	í
Mã số: 223 TÀI SẢN: - Giá trị hao mòn luỹ kế Thuyết _ minh:  31/12/2024 _
VND: (3.055.302.684.706) 01/01/2024: (3.000.156.961.182)
Mã số: 227 TÀI SẢN: 2. Tài sản cổ định vô hình Thuyết _ minh: 12 31/12/2024 _
VND: 34.742.825.241 01/01/2024: 37.611.322.887
Mã số: 228 TÀI SẢN: - Nguyên giá Thuyết _ minh:  31/12/2024 _
VND: 163.242.607.855 01/01/2024: 163.242.607.855
Mã số: 229 TÀI SẢN: - Giả tộ hao mỏn luỹ kế Thuyết _ minh:  31/12/2024 _
VND: (128.499.782.614) 01/01/2024: (125.631.284.968)
Mã số: 240 TÀI SẢN: III. Tài sản dở dang dài hạn Thuyết _ minh:  31/12/2024 _
VND: 6.369.610.766.433 01/01/2024: 6.629.710.273.959
Mã số: 242 TÀI SẢN: 1. Chi phí xây dựng cơ bản dở dang Thuyết _ minh: 13 31/12/2024 _
VND: 6.369.610.766.433 01/01/2024: 6.629.710.273.959
Mã số: 250 TÀI SẢN: IV. Đầu tư tài chính dài hạn Thuyết _ minh: 4 31/12/2024 _
VND: 301.381.762.917 01/01/2024: 290.868.721.513
Mã số: 251 TÀI SẢN: 1. Đầu tư vào công ty con Thuyết _ minh:  31/12/2024 _
VND: 468.846.333.510 01/01/2024: 468.846.333.510
Mã số: 252 TÀI SẢN: 2. Đầu tư vào công ty liên doanh, liên kết Thuyết _ minh:  31/12/2024 _
VND: 31.179.438.046 01/01/2024: 31.179.438.046
Mã số: 253 TÀI SẢN: 3. Đầu tư góp vốn vào đơn vị khác Thuyết _ minh:  31/12/2024 _
VND: 31.612.891.603 01/01/2024: 31.612.891.603
Mã số: 254 TÀI SẢN: 4. Dự phòng đầu tư tài chính dài hạn Thuyết _ minh:  31/12/2024 _
VND: (230.256.900.242) 01/01/2024: (240.769.941.646)
Mã số: 260 TÀI SẢN: V. Tài sản dài hạn khác Thuyết _ minh:  31/12/2024 _
VND: 140.547.709.256 01/01/2024: 140.925.744.190
Mã số: 261 TÀI SẢN: 1. Chi phí trả trước dài hạn Thuyết _ minh: 10 31/12/2024 _
VND: 140.547.709.256 01/01/2024: 140.925.744.190
Mã số: 270 TÀI SẢN: TỐNG CỘNG TÀI SẢN Thuyết _ minh:  31/12/2024 _
VND: 10.535.928.299.854 01/01/2024: 10.140.734.791.961

BBảng cân đối kế toán Analysis:
Mã: số NGUỒN VỐN:  Thuyết: minh 31/12/2024: VND 01/01/2024: VND
Mã: 300 NGUỒN VỐN: c. NỢ PHẢI TRẢ Thuyết:  31/12/2024: 8.983.401.606.968 01/01/2024: 8.459.417.588.825
Mã: 310 NGUỒN VỐN: I. Nợ ngắn hạn Thuyết:  31/12/2024: 6.353.532.791.437 01/01/2024: 6.014.755.519.619
Mã: 311 NGUỒN VỐN: 1. Phải trả người bán ngắn hạn Thuyết: 14 31/12/2024: 1.596.904.105.035 01/01/2024: 948.651.955.499
Mã: 312 NGUỒN VỐN: 2. Người mua trả tiền trước ngắn hạn Thuyết: 15 31/12/2024: 20.580.249.496 01/01/2024: 8.979.672.989
Mã: 313 NGUỒN VỐN: 3. Thuế và các khoản phải nộp Nhà nước Thuyết: 16 31/12/2024: 16.091.101.625 01/01/2024: 15.590.035.747
Mã: 314 NGUỒN VỐN: 4. Phải trả người lao động Thuyết:  31/12/2024: 64.651.358.360 01/01/2024: 76.814.503.426
Mã: 315 NGUỒN VỐN: 5. Chi phí phải trả ngắn hạn Thuyết: 17 31/12/2024: 1.757.357.645.878 01/01/2024: 2.135.968.638.783
Mã: 318 NGUỒN VỐN: 6. Doanh thu chưa thực hiện ngắn hạn Thuyết:  31/12/2024: 4.727.273 01/01/2024: -
Mã: 319 NGUỒN VỐN: 7. Phải trả ngắn hạn khác Thuyết: 19 31/12/2024: 337.023.007.038 01/01/2024: 341.719.945.920
Mã: 320 NGUỒN VỐN: 8. Vay và nợ thuê tài chính ngắn hạn Thuyết: 20 31/12/2024: 2.535.467.564.129 01/01/2024: 2.450.619.430.715
Mã: 321 NGUỒN VỐN: 9. Dự phòng phải trả ngắn hạn Thuyết: 18 31/12/2024: 2.114.874.722 01/01/2024: 12.791.241.298
Mã: 322 NGUỒN VỐN: 10. Quỹ khen thưởng, phúc lợi Thuyết:  31/12/2024: 23.338.157.881 01/01/2024: 23.620.095.242
Mã: 330 NGUỒN VỐN: II. Nợ dài hạn Thuyết:  31/12/2024: 2.629.868.815.531 01/01/2024: 2.444.662.069.206
Mã: 331 NGUỒN VỐN: 1. Phải trả người bán dài hạn Thuyết: 14 31/12/2024: 287.282.707.744 01/01/2024: 281.191.800.002
Mã: 333 NGUỒN VỐN: 2. Chi phí phải trả dài hạn Thuyết: 17 31/12/2024: 611.484.901.721 01/01/2024: 475.420.799.576
Mã: 337 NGUỒN VỐN: 3. Phải trả dài hạn khác Thuyết: 19 31/12/2024: 345.000.000 01/01/2024: 447.000.000
Mã: 338 NGUỒN VỐN: 4. Vay và nợ thuê tài chính dài hạn Thuyết: 20 31/12/2024: 1.684.284.955.551 01/01/2024: 1.618.854.239.855
Mã: 342 NGUỒN VỐN: 5. Dự phòng phải trả dài hạn Thuyết: 18 31/12/2024: 46.471.250.515 01/01/2024: 68.748.229.773
Mã: 400 NGUỒN VỐN: D. VÓN CHỦ SỞ HỮU Thuyết:  31/12/2024: 1.552.526.692.886 01/01/2024: 1.681.317.203.136
Mã: 410 NGUỒN VỐN: I. Vốn chủ sở hữu Thuyết: 21 31/12/2024: 1.552.526.692.886 01/01/2024: 1.681.317.203.136
Mã: 411 NGUỒN VỐN: 1. Vốn góp của chủ sở hữu Thuyết:  31/12/2024: 1.840.000.000.000 01/01/2024: 1.840.000.000.000
Mã: 411a NGUỒN VỐN: - Cổ phiếu phổ thông có quyền biểu quyết Thuyết:  31/12/2024: 1.840.000.000.000 01/01/2024: 1.840.000.000.000
Mã: 415 NGUỒN VỐN: 2. Cổ phiếu quỹ Thuyết:  31/12/2024: (41.070.000) 01/01/2024: (41.070.000)
Mã: 417 NGUỒN VỐN: 3. Chênh lệch tỷ giá hối đoái Thuyết:  31/12/2024: (397.837.384.978) 01/01/2024: (277.431.341.922)
Mã: 418 NGUỒN VỐN: 4. Quỹ đầu tư phát triển Thuyết:  31/12/2024: 29.908.837.239 01/01/2024: 29.908.837.239
Mã: 421 NGUỒN VỐN: 5. Lợi nhuận sau thuế chưa phân phổi Thuyết:  31/12/2024: 80.496.310.625 01/01/2024: 88.880.777.819
Mã: 421a NGUỒN VỐN: - LNST chưa phân phối lũy kế đến cuối năm trước Thuyết:  31/12/2024: 88.880.777.819 01/01/2024: 265.502.072.886
Mã: 421b NGUỒN VỐN: - LNST chưa phân phối năm nay Thuyết:  31/12/2024: (8.384.467.194) 01/01/2024: (176.621.295.067)
Mã: 440 NGUỒN VỐN: TỐNG CỘNG NGUỒN VỐN Thuyết:  31/12/2024: 10.535.928.299.854 01/01/2024: 10.140.734.791.961

Báo cáo kết quả hoạt động kinh doanh Analysis:
Mã: số CHỈ TIÊU:  Thuyết: minh Năm 2024: VND Năm 2023: VND
Mã: 01 CHỈ TIÊU: 1. Doanh thu bán hàng và cung cấp dịch vụ Thuyết: 23 Năm 2024: 15.411.656.765.794 Năm 2023: 13.331.709.287.541
Mã: 02 CHỈ TIÊU: 2. Các khoản giảm trừ doanh thu Thuyết: 24 Năm 2024: - Năm 2023: 759.321.350
Mã: 10 CHỈ TIÊU: 3. Doanh thu thuần bán hàng và cung cấp dịch vụ Thuyết:  Năm 2024: 15.411.656.765.794 Năm 2023: 13.330.949.966.191
Mã: 11 CHỈ TIÊU: 4. Giá vốn hàng bán Thuyết: 25 Năm 2024: 15.127.109.517.433 Năm 2023: 13.217.854.168.404
Mã: 20 CHỈ TIÊU: 5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ Thuyết:  Năm 2024: 284.547.248.361 Năm 2023: 113.095.797.787
Mã: 21 CHỈ TIÊU: 6. Doanh thu hoạt động tài chính Thuyết: 26 Năm 2024: 19.277.548.501 Năm 2023: 30.982.643.083
Mã: 22 CHỈ TIÊU: 7. Chi phí tài chính Thuyết: 27 Năm 2024: 98.930.106.069 Năm 2023: 131.144.343.340
Mã: 23 CHỈ TIÊU: Trong đó: chi phí lãi vay Thuyết:  Năm 2024: 108.271.256.672 Năm 2023: 129.643.777.529
Mã: 25 CHỈ TIÊU: 8. Chi phí bán hàng Thuyết: 28 Năm 2024: 50.777.341.289 Năm 2023: 53.536.637.631
Mã: 26 CHỈ TIÊU: 9. Chi phí quản lý doanh nghiệp Thuyết: 29 Năm 2024: 218.173.238.972 Năm 2023: 157.996.120.387
Mã: 30 CHỈ TIÊU: 10. Lợi nhuận thuần từ hoạt động kinh doanh Thuyết: 10. Lợi nhuận thuần từ hoạt động kinh doanh Năm 2024: (64.055.889.468) Năm 2023: (198.598.660.488)
Mã: 31 CHỈ TIÊU: 11. Thu nhập khác Thuyết: 30 Năm 2024: 83.123.386.886 Năm 2023: 39.045.921.417
Mã: 32 CHỈ TIÊU: 12. Chi phí khác Thuyết: 31 Năm 2024: 18.399.217.170 Năm 2023: 17.068.555.996
Mã: 40 CHỈ TIÊU: 13. Lợi nhuận khác Thuyết:  Năm 2024: 64.724.169.716 Năm 2023: 21.977.365.421
Mã: 50 CHỈ TIÊU: 14. Tổng lợi nhuận kế toán trước thuế Thuyết:  Năm 2024: 668.280.248 Năm 2023: (176.621.295.067)
Mã: 51 CHỈ TIÊU: 15. Chi phí thuế TNDN hiện hành Thuyết: 32 Năm 2024: 9.052.747.442 Năm 2023: -
Mã: 60 CHỈ TIÊU: 16. Lợi nhuận sau thuế TNDN Thuyết:  Năm 2024: _(8^84.467.194) Năm 2023: (176.621.295.067)

Báo cáo lưu chuyển tiền tệ Analysis:
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): Mã BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): CHỈ TIÊU	Thuyết_ BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): Năm 2024 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): Năm 2023
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): số BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): minh
1. LƯU CHUYÊN TIÈN TỪ HOẠT ĐỘNG KINH DOANH BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): VND BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): VND
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 01 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): Lợi nhuận trước thuế
Điều chỉnh cho câc khoản BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 668.280.248 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (176.621.295.067)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 02 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Khấu hao tài sản cố định và bất động sản đầu tư BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 60.084.423.809 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 63.391.551.785
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 03 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): ” Các khoản dự phòng BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (41.791.618.933) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (5.429.723.579)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 04 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Lãi, lỗ chênh lệch tỷ giá hối đoái do đánh giá íại các khoản mục tiền tệ có gốc ngoại tệ BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (109.205.103) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 143.648.752
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 05 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Lãi, lỗ từ hoạt động đầu tư BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (2.776.281.752) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (788.270.893)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 06 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Chi phí lãi vay BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 108.271.256.672 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 129.643.777.529
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 07 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Các khoản điều chỉnh khác BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp):  BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (32.337.005)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 08 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 3. Lợi nhuận từ hoạt động kinh doanh trước thay đổi vốn lưu động BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 124.346.854.941 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 10.307.351.522
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 09 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Tăng, giảm các khoản phải thu BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (190.678.030.082) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (49.171.064.158)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 10 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Tăng, giảm hàng tồn kho BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (440.657.796.905) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 392.853.199.798
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 11 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): “ Tăng, giảm các khoản phải trả BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 620.892.126.700 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (58.184.750.579)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 12 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): ~ Tăng, giảm chi phí trả trước BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 6.858.235.108 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 10.741.376.937
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 14 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Tiền ỉãi vay đã trả BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (108.683.181.672) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (127.533.187.674)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 15 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Thuế thu nhập doanh nghiệp đã nộp BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp):  BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (1,366.508.935)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 16 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Tiền thu khác từ hoạt động kinh doanh BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 278.008.695 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 16.390.000
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 17 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): - Tiền chi khác cho hoạt động kinh doanh BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (1.080.000) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp):
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 20 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): Lưu chuyền tiền thuần từ hoạt động kinh doanh
II. LỰU CHUYỂN TIỀN TỪ HOẠT ĐỘNG ĐẦU TƯ BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 12.355.136.785 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 177.662.806.911
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 21 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 1. Tiền chi đẻ mua sắm, xây dựng tài sản cố định và tài sản dài hạn khác BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (15.802.573.134) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (28.704.410.989)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 22 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 2. Tiền thu từ thanh lý, nhượng bán tài sản cố định và các tài sản dài hạn khác BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 1.626.815.400 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): -
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 23 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 3. Tiền chi cho vay, mua các công cụ nợ của đơn vị khác BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (8.627.790.000) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): -
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 27 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 4. Tiền thu lâi cho vay, cồ tức và lợi nhuận được chia BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 978.612.472 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 874.289.898
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 30 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): Lưu chuyển tiền thuần từ hoạt động đầu tư
III. LƯU CHUYÊN TIỀN TỪ HOẠT ĐỘNG TÀI CHÍNH BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (21.824.935.262) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (27.830.121.091)
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 33 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 1. Tiền thu từ đí vay BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 4.369.975.646.841 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 4.583.952.112.627
BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 34 BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): 2. Tiền trả nợ gốc vay BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024
(Theo phương pháp gián tiếp): (4.294.204.139.998) BÁO CÁO LƯU CHUYẺN TIỀN TỆ RIÊNG
Năm 2024

In [46]:
def get_phobert_features(text):
    """Trích xuất đặc trưng từ văn bản bằng mô hình PhoBERT."""
    inputs = tokenizer(text, return_tensors="pt", max_length=512, truncation=True)

    with torch.no_grad():
        outputs = model(**inputs)

    # 'last_hidden_state' chứa các embedding của từng token
    last_hidden_state = outputs.last_hidden_state

    # Embedding của token [CLS] (biểu diễn cho toàn bộSequence)
    cls_embedding = last_hidden_state[:, 0, :]

    return last_hidden_state, cls_embedding

# Đưa combined_text vào PhoBERT để trích xuất đặc trưng
all_token_embeddings, cls_embedding = get_phobert_features(combined_text)

print("Nội dung của combined_text trước khi đưa vào PhoBERT:\n", combined_text)
all_token_embeddings, cls_embedding = get_phobert_features(combined_text)

IndexError: index out of range in self